export const SITE_NAME = "Unbody";
export const SITE_TITLE = "The AI-native backend";
export const SITE_DESCRIPTION ="An open-source, modular backend for building AI-native software that understands, reasons, and acts on knowledge — instead of just data.";
export const SITE_URL = "https://unbody.io";

export const SITE_KEYWORDS = [
  "Custom AI",
  "AI-Native",
  "AI-first applications",
  "AI applications",
  "single API",
  "user-friendly",
  "accessible",
  "cost-effective",
  "data-driven insights",
  "AI for everyone",
  "No AI expertise required",
  "one-line integration",
  "RAG",
  "vector search",
  "knowledge graph",
  "reasoning",
  "actionable insights",
  "simplify AI deployment",
  "Custom AI engine development",
  "seamless data integration platform",
  "AI application simplification",
  "Data aggregation",
  "AI data preparation",
  "scalable AI applications",
  "AI for developers",
  "Streamline AI projects",
  "enhance business operations",
  "empower innovation",
  "unlock AI potential",
  "AI graphql",
  "JS AI",
  "LLM Javascript",
  "LLM graphql",
];
